image:
  file: .gitpod.Dockerfile

tasks:
  - init: bash -c "sudo pip3 install poetry && curl https://raw.githubusercontent.com/IgnisDa/printr/main/get-printr.sh | sh -s -- --yes && /workspace/Resourceium/tools/init-db.sh && git config --global pull.rebase true && poetry config virtualenvs.in-project true"

ports:
  - port: 3000
    visibility: public
  - port: 8080
    visibility: public
  - port: 8000
    visibility: public

vscode:
  extensions:
    - redhat.java
    - octref.vetur
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - mhutchie.git-graph
    - cweijan.vscode-database-client2
    - ms-python.python
