image:
  file: .gitpod.Dockerfile

tasks:
  - init: bash -c "/workspace/Resourceium/tools/init-db.sh && git config --global pull.rebase true"

ports:
  - port: 3000
    visibility: public
  - port: 8000
    visibility: public

vscode:
  extensions:
    - redhat.java
    - octref.vetur
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - mhutchie.git-graph
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
