version: "3.8"

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      spring.profiles.active: dev
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./server/:/app
      - server_data:/root/.m2/repository

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_URL: http://localhost:8000/
    depends_on:
      - server
    volumes:
      - ./client/:/app
      - client_data:/app/node_modules

  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: server_db
    volumes:
      - data:/var/lib/postgresql/data

# Volumes
volumes:
  server_data:
  client_data:
  data:
