version: "3.8"

# Define services
services:
  # App backend service
  server:
    # Configuration for building the docker image for the backend service
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      spring.profiles.active: dev
    ports:
      - "8000:8000"
    depends_on:
      - database # This service depends on mysql. Start that first.
    volumes:
      - ./server/:/app
      - server_data:/root/.m2/repository

  # Frontend Service
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client/:/app
      - /app/node_modules

  # Database Service (Mysql)
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: username
      MYSQL_DATABASE: server_db
    volumes:
      - db_data:/var/lib/mysql

# Volumes
volumes:
  db_data:
  server_data:
