version: "3.8"

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      spring.profiles.active: dev
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./server/:/app
      - server_data:/root/.m2/repository

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_URL: http://localhost:8000/
    depends_on:
      - server
    volumes:
      - ./client/:/app
      - client_data:/app/node_modules

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: username
      MYSQL_DATABASE: server_db
    volumes:
      - db_data:/var/lib/mysql

# Volumes
volumes:
  db_data:
  server_data:
  client_data:
