version: "3.8"

services:
  development-machine:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    
    container_name: resourceium

    volumes:
      - ..:/workspace/Resourceium:cached
      - server_data:/home/developr/.m2/repository
      - postgres_data:/var/lib/postgresql/data

    command: sleep infinity

volumes:
  server_data:
  postgres_data:
