version: "3.8"

services:
  development-machine:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace/Resourceium:cached
      - server_data:/home/vscode/.m2/repository
      - cypress-cache:/home/vscode/Cypress
      - /tmp/.X11-unix:/tmp/.X11-unix

    command: sleep infinity
    network_mode: service:db
    user: vscode
    environment:
      CYPRESS_VIDEO: "false"
      DISPLAY:

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./setup-storage:/docker-entrypoint-initdb.d/setup-storage.sh
    environment:
      POSTGRES_PASSWORD: password

volumes:
  postgres-data:
  server_data:
  cypress-cache:
